### ISSUE TITLE
확장

### ISSUE THREAD

**Issue by Comet5** [SelfGuideTeam/SelfGuideBook#64]
# 수정완료
- 링크, 이미지 넣기 할때 생기는 팝업이 확장에 가려서 안보임
     - Z index 설정?

- 특정사이트(stackoverflow 등)에서의 style이 확장의 style에도 영향을 줌
     - class 이름 주기
     -- shadow dom으로 해결
- 확장을 켰을때 로그인, 내가이드북 불러오기, 로그아웃 등 로딩이 필요한 상황
     - 로딩화면을 만들어서 딴짓못하게
     -- disable줘서 해결

- 현재 에디터의 내용이 저장이 됐는지 안됐는지 확인할 방법이 필요함
여러 페이지에 확장이 켜져있을 때 누구는 전에 저장한거고 누구는 방금저장한게 될 수있음
     - 서버에 저장할때, 에디터에 글쓰기할때 리스너에서 변수를 바꿔주면 될듯

- shadow dom 때문에 svg태그를 editorhtml에 넣었는데   드롭다운이 맨 왼쪽에 붙음

- 로그아웃 한 상태에서 home버튼 css 조절, 에디터 사이즈 조절(기본, full)

- 페이지가 다 로드되기전에 확장이 실행되는거 막아야됨

- 작성을 멈추고 1초가 지나면 자동으로 서버에 저장함

- 중복된 이름으로 저장하려고 할때 서버에서 결과값으로 중복된값이라고 알려줘야될듯

- 캡처후 이미지 편집창에서 편집한 이미지로 에디터에 들어가지 않고 초기의 이미지로 들어감

 # 수정중

# 생각
- HTML코드만으로 PDF로 저장하는데 있어서 변수가 너무많음 에디터에 보이는 그대로 PDF로 저장이 안됨 => 페이지별로 저장 불가능
     웹사이트에서 PDF로 저장하는게 나을듯

**Comment by C0Colaca18189874** [comment]
- 글 잘림

- 줄 간격 기능 안됨

- 인용문 기능 안됨

- 이미지 업로드 안된 이후 창 새로고침 하면 글 입력이 안 됨

- 글 드래그후 에디터 효과 버튼 하나 누를 때마다 드래그가 풀림

**Comment by Comet5** [comment]
> * 글 드래그후 에디터 효과 버튼 하나 누를 때마다 드래그가 풀림 
??

**Comment by Comet5** [comment]
close
